/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_a_ramos
 */
public class AuxConta extends javax.swing.JFrame {

    /**
     * Creates new form AuxConta
     */
    public AuxConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAuxConta = new javax.swing.JPanel();
        Pcadastro = new javax.swing.JPanel();
        lCadastro = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        lUsuário = new javax.swing.JLabel();
        fUsuario = new javax.swing.JTextField();
        lSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lCSenha = new javax.swing.JLabel();
        pfCSenha = new javax.swing.JPasswordField();
        bRegistra = new javax.swing.JButton();
        lImagem = new javax.swing.JLabel();
        Pesquecisenha = new javax.swing.JPanel();
        lEsquecisenha = new javax.swing.JLabel();
        lnome = new javax.swing.JLabel();
        fnome = new javax.swing.JTextField();
        lusuario = new javax.swing.JLabel();
        fusuario = new javax.swing.JTextField();
        lnovasenha = new javax.swing.JLabel();
        fnovasenha = new javax.swing.JPasswordField();
        lcsenha = new javax.swing.JLabel();
        fcsenha = new javax.swing.JPasswordField();
        bRecadastro = new javax.swing.JButton();
        limagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setPreferredSize(new java.awt.Dimension(730, 541));

        pAuxConta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pAuxConta.setPreferredSize(new java.awt.Dimension(730, 541));
        pAuxConta.setLayout(new java.awt.CardLayout());

        Pcadastro.setForeground(new java.awt.Color(255, 255, 255));
        Pcadastro.setPreferredSize(new java.awt.Dimension(730, 541));
        Pcadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lCadastro.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lCadastro.setForeground(new java.awt.Color(0, 204, 204));
        lCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCadastro.setText("Faça Cadastro do Usuário");
        Pcadastro.add(lCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 50));

        lNome.setForeground(new java.awt.Color(255, 255, 255));
        lNome.setText("Nome");
        Pcadastro.add(lNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, -1));

        fNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNomeKeyPressed(evt);
            }
        });
        Pcadastro.add(fNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, -1));

        lUsuário.setForeground(new java.awt.Color(255, 255, 255));
        lUsuário.setText("Usuário");
        Pcadastro.add(lUsuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 50, -1));

        fUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fUsuarioKeyPressed(evt);
            }
        });
        Pcadastro.add(fUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, -1));

        lSenha.setForeground(new java.awt.Color(255, 255, 255));
        lSenha.setText("Senha");
        Pcadastro.add(lSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenhaKeyPressed(evt);
            }
        });
        Pcadastro.add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, -1));

        lCSenha.setForeground(new java.awt.Color(255, 255, 255));
        lCSenha.setText("Confimar Senha");
        Pcadastro.add(lCSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        pfCSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfCSenhaKeyPressed(evt);
            }
        });
        Pcadastro.add(pfCSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 200, -1));

        bRegistra.setText("Registrar-se");
        bRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistraActionPerformed(evt);
            }
        });
        Pcadastro.add(bRegistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 100, -1));

        lImagem.setForeground(new java.awt.Color(255, 255, 255));
        lImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgTela/space.jpeg"))); // NOI18N
        lImagem.setPreferredSize(new java.awt.Dimension(1024, 768));
        Pcadastro.add(lImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -230, 740, 2400));

        pAuxConta.add(Pcadastro, "Pcadastro");

        Pesquecisenha.setPreferredSize(new java.awt.Dimension(730, 541));
        Pesquecisenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lEsquecisenha.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lEsquecisenha.setForeground(new java.awt.Color(0, 204, 204));
        lEsquecisenha.setText("Esqueci minha senha");
        Pesquecisenha.add(lEsquecisenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        lnome.setForeground(new java.awt.Color(255, 255, 255));
        lnome.setText("Nome");
        Pesquecisenha.add(lnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        fnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnomeKeyPressed(evt);
            }
        });
        Pesquecisenha.add(fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, -1));

        lusuario.setForeground(new java.awt.Color(255, 255, 255));
        lusuario.setText("Usuário");
        Pesquecisenha.add(lusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        fusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusuarioActionPerformed(evt);
            }
        });
        fusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fusuarioKeyPressed(evt);
            }
        });
        Pesquecisenha.add(fusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, -1));

        lnovasenha.setForeground(new java.awt.Color(255, 255, 255));
        lnovasenha.setText("Nova Senha");
        Pesquecisenha.add(lnovasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        fnovasenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnovasenhaKeyPressed(evt);
            }
        });
        Pesquecisenha.add(fnovasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, -1));

        lcsenha.setForeground(new java.awt.Color(255, 255, 255));
        lcsenha.setText("Confimar senha");
        Pesquecisenha.add(lcsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        fcsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fcsenhaKeyPressed(evt);
            }
        });
        Pesquecisenha.add(fcsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 200, -1));

        bRecadastro.setText("Recadastrar");
        bRecadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRecadastroActionPerformed(evt);
            }
        });
        Pesquecisenha.add(bRecadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 100, -1));

        limagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgTela/space.jpeg"))); // NOI18N
        limagem.setText("jLabel2");
        limagem.setPreferredSize(new java.awt.Dimension(730, 541));
        Pesquecisenha.add(limagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-960, -180, 1860, 770));

        pAuxConta.add(Pesquecisenha, "Pesquecisenha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pAuxConta, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAuxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistraActionPerformed
        //pega a senha crip e transforma em texto
        String senhaString = new String(pfSenha.getPassword());
        String senhaCString = new String(pfCSenha.getPassword());
       
        if(senhaString.equals(senhaCString)){
            Usuarios usu = new Usuarios();
            if(usu.cadastrar(fUsuario.getText(), senhaString, fNome.getText())){
                fNome.setText("");
                fUsuario.setText("");
                pfSenha.setText("");
                pfCSenha.setText("");                                             
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "  Falha ao cadastrar. \n(Tente outro Usuário)");
                pfSenha.setText("");
                pfCSenha.setText("");               
            }
        }else{
            JOptionPane.showMessageDialog(null, "Os campos de senha não correspondem.");
            pfSenha.setText("");
            pfCSenha.setText("");
        }
    }//GEN-LAST:event_bRegistraActionPerformed

    private void bRecadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRecadastroActionPerformed
        String novasenha = new String(fnovasenha.getPassword());
        String novacsenha = new String(fcsenha.getPassword());
        if(novasenha.equals(novacsenha)){
            Usuarios usu = new Usuarios();
            if(!Usuarios.validacaoCadastro(fnome.getText(), fusuario.getText())){
                fusuario.requestFocus();
                fusuario.setText("");
            }
            if(usu.aterarsenha(fusuario.getText(), novasenha,fnome.getText())){
                fnome.setText("");
                fusuario.setText("");
                fnovasenha.setText("");
                fcsenha.setText("");                                             
                JOptionPane.showMessageDialog(null, "Senha alterada com sucesso!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao alterar sua senha.");
                fnovasenha.setText("");
                fcsenha.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Verifique sua senha novamente.");
        }
    }//GEN-LAST:event_bRecadastroActionPerformed

////CADASTRO
    private void fNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNomeKeyPressed
        if (evt.getKeyCode() == 10)           
            fUsuario.requestFocus();
    }//GEN-LAST:event_fNomeKeyPressed
    private void fUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fUsuarioKeyPressed
        if (evt.getKeyCode() == 10) 
            pfSenha.requestFocus();
    }//GEN-LAST:event_fUsuarioKeyPressed
    private void pfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyPressed
        if (evt.getKeyCode() == 10)           
            pfCSenha.requestFocus();
    }//GEN-LAST:event_pfSenhaKeyPressed
    private void pfCSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfCSenhaKeyPressed
        getRootPane().setDefaultButton(bRegistra);
    }//GEN-LAST:event_pfCSenhaKeyPressed

//ESQUECISENHA
    private void fnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnomeKeyPressed
        if (evt.getKeyCode() == 10)           
            fusuario.requestFocus();
    }//GEN-LAST:event_fnomeKeyPressed
    private void fusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fusuarioKeyPressed
        if (evt.getKeyCode() == 10)           
            fnovasenha.requestFocus();
    }//GEN-LAST:event_fusuarioKeyPressed
    private void fnovasenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnovasenhaKeyPressed
        if (evt.getKeyCode() == 10)           
            fcsenha.requestFocus();
    }//GEN-LAST:event_fnovasenhaKeyPressed
    private void fcsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcsenhaKeyPressed
        getRootPane().setDefaultButton(bRecadastro);
    }//GEN-LAST:event_fcsenhaKeyPressed
    private void fusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusuarioActionPerformed
//        if(!Usuarios.validacaoCadastro(fnome.getText(), fusuario.getText())){
//            JOptionPane.showMessageDialog(null,"Usuário incorreto.");
//            fusuario.requestFocus();
//            fusuario.setText("");
//        }
    }//GEN-LAST:event_fusuarioActionPerformed

    public void iniciar(String nomePainel) {        
        AuxConta ac = new AuxConta();
            
        CardLayout card = (CardLayout)ac.pAuxConta.getLayout();
        card.show(ac.pAuxConta, nomePainel);
        
        ac.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pcadastro;
    private javax.swing.JPanel Pesquecisenha;
    private javax.swing.JButton bRecadastro;
    private javax.swing.JButton bRegistra;
    private javax.swing.JTextField fNome;
    private javax.swing.JTextField fUsuario;
    private javax.swing.JPasswordField fcsenha;
    private javax.swing.JTextField fnome;
    private javax.swing.JPasswordField fnovasenha;
    private javax.swing.JTextField fusuario;
    private javax.swing.JLabel lCSenha;
    private javax.swing.JLabel lCadastro;
    private javax.swing.JLabel lEsquecisenha;
    private javax.swing.JLabel lImagem;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lUsuário;
    private javax.swing.JLabel lcsenha;
    private javax.swing.JLabel limagem;
    private javax.swing.JLabel lnome;
    private javax.swing.JLabel lnovasenha;
    private javax.swing.JLabel lusuario;
    private javax.swing.JPanel pAuxConta;
    private javax.swing.JPasswordField pfCSenha;
    private javax.swing.JPasswordField pfSenha;
    // End of variables declaration//GEN-END:variables
}
