/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import javax.swing.JOptionPane;
import outerspace.*;
/**
 *
 * @author gabriel_a_ramos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNewGame = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bRanking = new javax.swing.JButton();
        lOuter = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Outer Space");
        setPreferredSize(new java.awt.Dimension(730, 541));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bNewGame.setText("New Game");
        bNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewGameActionPerformed(evt);
            }
        });
        getContentPane().add(bNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 100, -1));

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, -1));

        bRanking.setText("Ranking");
        bRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRankingActionPerformed(evt);
            }
        });
        getContentPane().add(bRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, -1));

        lOuter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgTela/Tela_principal_1.png"))); // NOI18N
        lOuter.setText("jLabel1");
        getContentPane().add(lOuter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 510, -1));

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgTela/space.jpeg"))); // NOI18N
        lFundo.setText("jLabel2");
        getContentPane().add(lFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2260, -1220, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewGameActionPerformed
        OuterSpace ng = new OuterSpace();
    }//GEN-LAST:event_bNewGameActionPerformed

    private void bRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRankingActionPerformed
        JOptionPane.showMessageDialog(null, "      EM MANUTENÇÃO !");
    }//GEN-LAST:event_bRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void jogo(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bNewGame;
    private javax.swing.JButton bRanking;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lOuter;
    // End of variables declaration//GEN-END:variables
}
